In [1]:
import numpy as np
import cv2
import sys
import os

import matplotlib.pyplot as plt

In [3]:
x = np.arange(8)

print(x)

[0 1 2 3 4 5 6 7]


In [8]:
tx = x*1.5                                # forward
print(tx)

[ 0.   1.5  3.   4.5  6.   7.5  9.  10.5]


In [6]:
x1 = np.arange(16)
print(x1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [7]:
tx1 = x1 / 1.5                              # Backward
print(tx1)                 

[ 0.          0.66666667  1.33333333  2.          2.66666667  3.33333333
  4.          4.66666667  5.33333333  6.          6.66666667  7.33333333
  8.          8.66666667  9.33333333 10.        ]


In [15]:
## 키보드 이벤트

img = cv2.imread('../ch_1/figure/fig/puppy.bmp', cv2.IMREAD_GRAYSCALE)

if img is None:
    print('image read failed')
    sys.exit()
    
img2 = img.copy()    
    
cv2.imshow('img', img)

while True:
    key = cv2.waitKey()
    if key == 27:
        break
        
    elif key == ord('i'):
        img = 255 - img                    # 색반전
        cv2.imshow('img', img)

    elif key == ord('e'):
        img = cv2.Canny(img, 50, 150)
        cv2.imshow('img', img)
        
    elif key == ord('r'):
        img = img2.copy()
        cv2.imshow('img', img)
        
    elif key == ord('s'):
        img1 = img.copy()
        cv2.imwrite('../ch_1/figure/fig/save.png', img1)
        
        
cv2.destroyAllWindows()

[mouse callback](https://076923.github.io/posts/Python-opencv-39/)

In [5]:
## 마우스 이벤트

def call_mouse(event, x, y, flags, param):
#     global oldx, oldy

    if event == cv2.EVENT_LBUTTONDOWN:
        oldx, oldy = x, y
        print('EVENT_LBUTTONDOWN: %d, %d' % (x, y))

    elif event == cv2.EVENT_LBUTTONUP:
        print('EVENT_LBUTTONUP: %d, %d' % (x, y))

    elif event == cv2.EVENT_MOUSEMOVE:
        if flags & cv2.EVENT_FLAG_LBUTTON:
            cv2.line(img, (oldx, oldy), (x, y), (0, 0, 255), 4, cv2.LINE_AA)
            cv2.imshow('image', img)
            oldx, oldy = x, y


img = np.ones((480, 640, 3), dtype=np.uint8) * 255

cv2.namedWindow('image')
cv2.setMouseCallback('image', call_mouse, img) #항상 창을 띄우고 호출

cv2.imshow('image', img)
cv2.waitKey()

cv2.destroyAllWindows()

In [21]:
## 마우스 이벤트

def mouse_call(event, x, y, flags, param):
    
    global oldx, oldy
    
    if event == cv2.EVENT_LBUTTONDOWN:
        oldx, oldy = x, y                                 # oldx, oldy는 현재 누른 시점의 x, y
        
        
    elif event == cv2.EVENT_MOUSEMOVE:
        if flags == cv2.EVENT_FLAG_LBUTTON:                      # flags 사용하기
            cv2.line(img, (oldx, oldy), (x, y), (0, 0, 0), 4, cv2.LINE_AA)
            cv2.imshow('image', img)
            oldx, oldy = x, y

img = np.ones((600, 800, 3), np.uint8)*255

cv2.namedWindow('image')

# setMouseCallback(windowName, onMouse [, param]) -> None
cv2.setMouseCallback('image', mouse_call, img)
                              # 정의된 함수 사용  
cv2.imshow('image', img)

while True:
    key = cv2.waitKey()
    if key == ord('s'):
        img_1 = img.copy()
        cv2.imwrite('../ch_1/figure/fig/name.png', img_1)
        
    elif key == 27:
        break


cv2.destroyAllWindows()

In [6]:
## 트랙바

def call_track(pos):
    print(pos)
    img[:] = pos
    cv2.imshow('image', img)

img = np.zeros((500, 600), np.uint8)

cv2.namedWindow('image')

#  createTrackbar(trackbarName, windowName, value, count, onChange) -> None
cv2.createTrackbar('level', 'image', 0, 255, call_track)

cv2.imshow('image', img)

cv2.waitKey()
cv2.destroyAllWindows()

1
3
4
6
7
8
9
10
12
14
16
18
21
23
24
26
29
32
34
37
42
46
49
54
58
62
64
69
70
72
73
74
75
77
80
82
86
88
91
93
95
97
98
100
102
103
105
108
109
112
114
115
117
118
119
120
121
123
125
126
128
129
130
131
133
135
136
137
138
139
140
141
142
143
144
146
149
153
158
162
166
169
172
174
176
177
180
181
182
183
185
187
189
192
194
195
199
201
205
206
209
212
213
214
216
218
219
220
221
222
223
224
225
226
228
229
230
229
228
227
226
225
224
223
221
220
219
216
215
213
211
208
207
206
204
202
200
199
195
192
188
186
182
178
176
173
168
164
158
155
150
146
141
137
133
129
123
120
116
113
107
102
96
91
86
82
78
74
71
67
62
58
55
52
51
50
48
45
42
40
38
36
33
30
27
24
20
18
16
15
14
15
17
21
23
26
31
35
40
44
50
53
56
60
63
67
73
79
87
96
104
116
125
133
142
149
154
158
163
167
171
174
177
180
183
184
187
188
189
190
192
193
195
196
200
203
209
214
219
223
227
230
231
233
234
236
238
242
246
250
253
254
255
252
249
245
241
238
233
231
226
222
218
215
211
206
203
199
197
195
194
191
190
188
18

In [9]:
## 흑백사진에 트랙바 넣기

def call_track(pos):
#     print(pos)

#     img[:] = img*(pos/255)                        # 여기를 수정한다
    img[:] = np.round(img1*(pos/255), 0)                                 # 하지만 그냥 하면 img에 덮어쓰기 때문에 img1을 copy하여 만들어 넣는다.
    cv2.imshow('image', img)

img = cv2.imread('../ch_1/figure/fig/puppy.bmp', cv2.IMREAD_GRAYSCALE)
img1 = img.copy()

if img is None:
    print('failed')
    sys.exit()
    
cv2.namedWindow('image')

cv2.createTrackbar('level', 'image', 0, 255, call_track)

cv2.imshow('image', img)                             # 디폴트 값은 WINDOW_AUTOSIZE 로 크기조절 불가능

cv2.waitKey()
cv2.destroyAllWindows()

In [1]:
import numpy as np
import cv2
import sys
import os

import matplotlib.pyplot as plt